// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect"

type Docusign struct {
	Demo                 bool   `mapstructure:"demo"`
	DocusignClientId     string `mapstructure:"docusign-client-id"`
	DocusignClientSecret string `mapstructure:"docusign-client-secret"`
	RedirectUri          string `mapstructure:"redirect-uri"`
	RefreshToken         string `mapstructure:"refresh-token"`
	Configure            bool   `mapstructure:"configure"`
	AccountId            string `mapstructure:"account-id"`
	IncludeSigningGroups bool   `mapstructure:"include-signing-groups"`
	IncludeClm           bool   `mapstructure:"include-clm"`
	ClmBaseUrl           string `mapstructure:"clm-base-url"`
	BaseUrl              string `mapstructure:"base-url"`
	Oauth2Token          string `mapstructure:"oauth2-token"`
}

func (c *Docusign) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Docusign) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Docusign) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *Docusign) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Docusign) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Docusign) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
