name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=3m

  go-test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      ACCOUNTID: ${{ secrets.ACCOUNTID }}
      CLIENTID: ${{ secrets.CLIENTID }}
      CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
      REDIRECTURI: ${{ secrets.REDIRECTURI }}
      REFRESHTOKEN: ${{ secrets.REFRESHTOKEN }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run go tests
        run: (set -o pipefail && go test -v -covermode=atomic -json -race ./... | tee test.json)
      - name: Annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  integration-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      ACCOUNTID: ${{ secrets.ACCOUNTID }}
      CLIENTID: ${{ secrets.CLIENTID }}
      CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
      REDIRECTURI: ${{ secrets.REDIRECTURI }}
      REFRESHTOKEN: ${{ secrets.REFRESHTOKEN }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-docusign
        run: go build -o baton-docusign ./cmd/baton-docusign
      - name: Validate capabilities
        run: |
          ./baton-docusign \
            --account-id "$ACCOUNTID" \
            --clientId "$CLIENTID" \
            --clientSecret "$CLIENTSECRET" \
            --redirect-uri "$REDIRECTURI" \
            --refresh-token "$REFRESHTOKEN" \
          capabilities
      - name: Run basic sync test
        run: |
          ./baton-docusign \
            --account-id "$ACCOUNTID" \
            --clientId "$CLIENTID" \
            --clientSecret "$CLIENTSECRET" \
            --redirect-uri "$REDIRECTURI"\
            --refresh-token "$REFRESHTOKEN"\
            --log-level debug \
            --file sync.c1z

          if [ ! -f "sync.c1z" ]; then
            echo "Error: File sync.c1z was not generated."
            exit 1
          fi
      - name: List Baton Commands
        run: ./baton-docusign --help
